# tasks/main.yml
---

- name: Update all packages on CentOS 7
  yum:
    name: "*"
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Update all packages on Rocky Linux
  yum:
    name: "*"
    state: latest
  when: ansible_distribution == "Rocky"

- name: Update all packages on Ubuntu
  apt:
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_distribution == "Ubuntu"