global:
  imagePullSecrets: [ ]
  istioNamespace: istio-system
  externalIstiod: false
  remotePilotAddress: ""
  platform: ""
  ipFamilyPolicy: ""
  ipFamilies: [ ]
base:
  enableCRDTemplates: false
  validationURL: ""
  validationCABundle: ""
  enableIstioConfigCRDs: true
defaultRevision: "default"
experimental:
  stableValidationPolicy: false