---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-nas-csi
  namespace: app
provisioner: nas.csi.ncloud.com
parameters:
  server: 169.254.0.20
  share: /n2598262_appadmin
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
- hard
- nolock
- nfsvers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: mysql-nas-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: stage-mysql-pvc
#   namespace: mysql
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 250Gi
#   storageClassName: mysql-nas-csi