apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: mysql
  labels:
    app: mysql-master
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-master

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: mysql
  labels:
    app: mysql-slave
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-slave
