apiVersion: v1
kind: Service
metadata:
  name: mysql-master-external
  namespace: mysql
  labels:
    app: mysql-master
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
spec:
  type: LoadBalancer
  selector:
    app: mysql-master
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-master-nodeport
#   namespace: mysql
#   labels:
#     app: mysql-master
#   annotations:
#     service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"
#     service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
#     service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
# spec:
#   type: NodePort
#   selector:
#     app: mysql-master
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-external
  namespace: mysql
  labels:
    app: mysql-slave
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
spec:
  type: LoadBalancer
  selector:
    app: mysql-slave
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: mysql-gateway
#   namespace: mysql
# spec:
#   selector:
#     istio: ingress
#   servers:
#   - port:
#       number: 3306
#       name: tcp-mysql
#       protocol: TCP
#     hosts:
#     - "*"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: mysql-master
#   namespace: mysql
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - mysql-gateway
#   tcp:
#   - match:
#     - port: 3306
#     route:
#     - destination:
#         host: mysql-master
#         port:
#           number: 3306
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: mysql-master
#   namespace: mysql
# spec:
#   host: mysql-master
#   trafficPolicy:
#     loadBalancer:
#       simple: ROUND_ROBIN
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: mysql-gateway
#   namespace: mysql
# spec:
#   selector:
#     istio: ingress
#   servers:
#   - port:
#       number: 3306
#       name: tcp
#       protocol: TCP
#     hosts:
#     - "*"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: mysql-vs
#   namespace: mysql
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - mysql-gateway
#   http:
#   - match:
#     - port: 3306
#     route:
#     - destination:
#         host: mysql-master
#         port:
#           number: 3306
